version: '3'
services:
  frr1:
    image: frrouting/frr
    container_name: frr1
    privileged: true
    volumes:
      - ./frr/frr1.conf:/etc/frr/frr.conf
    networks:
      sdwan:
        ipv4_address: 10.10.10.2

  frr2:
    image: frrouting/frr
    container_name: frr2
    privileged: true
    volumes:
      - ./frr/frr2.conf:/etc/frr/frr.conf
    networks:
      sdwan:
        ipv4_address: 10.10.10.3

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wireguard:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      sdwan:
        ipv4_address: 10.10.10.4

  firewall:
    image: alpine
    container_name: firewall
    privileged: true
    volumes:
      - ./firewall/rules.sh:/rules.sh
    entrypoint: ["/bin/sh", "/rules.sh"]
    networks:
      sdwan:
        ipv4_address: 10.10.10.5

networks:
  sdwan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
