name: CI/CD SD-WAN Lab

on:
  push:
    paths:
      - '**.yml'
      - '**.sh'
      - '**.conf'
      - '**.tf'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate Docker Compose
      run: docker-compose config -q
    - name: Validate Ansible syntax
      run: ansible-playbook --syntax-check ansible/playbook.yml
